version: '3.9'
services:
  db:
    container_name: hsqldb-booking
    image: blacklabelops/hsqldb
    environment:
      - HSQLDB_USER=sa
      - HSQLDB_PASSWORD=password
      - HSQLDB_DATABASE_ALIAS=booking
    ports:
      - "9001:9001"
    volumes:
      - hsqldb:/var/lib/hsqldb

  booking-backend:
    container_name: booking-app
    restart: on-failure
    image: awex
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: "Dockerfile"

volumes:
  hsqldb:
