spring:
  datasource:
    url: jdbc:hsqldb:hsql://db:9001/booking
    username: sa
    password: password
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.HSQLDialect